### ISSUE TITLE
SurfaceArea cannot be NULL for LookupAsync function

### ISSUE THREAD

**Issue by HansBroos** [postcode-nl/PostcodeNl_Api_RestClient#2]
When I use the LookupAsync function with these parameters: Postalcode: 4681SV, Housenumber: 7, I get an error that SurfaceArea cannot be NULL in VB.NET

Codeline: Dim addressType As String = postnl.LookupAsync("4681SV", 7).Result.AddressType
InnerException: "Error converting value {null} to type 'System.Int32'. Path 'surfaceArea', line 1, position 388."

**Comment by DaanBroekhof** [comment]
Hi Hans,

This is the support issue tracker for the PHP example implementation of our address API, and your question is probably regarding a VB.net implementation of our address API? 

We have no access to your VB.net code, so as such we cannot see what is incorrect.

Seeing the error though, I would think that whomever implemented the interacting code did not realize that the 'surfaceArea' field can be empty ('null') - for example for postal boxes.

If you have more questions, please send a mail to tech <at> postcode.nl.

**Comment by HansBroos** [comment]
Yes, that is correct. I'll look for another solution.
Thanks for the quick response!
