### ISSUE TITLE
PHP 7 compatibility

### ISSUE THREAD

**Issue by slokhorst** [postcode-nl/PostcodeNl_Api_RestClient#4]
I would like to use this library with PHP 7.0. The composer file however states that only PHP 5.X (>5.2) is supported.

I have briefly tested the code and it seems to work fine with PHP 7. Could you please update `composer.json`? Thanks!

**Comment by stefandoorn** [comment]
PR in #5 :)

**Comment by arjenschol** [comment]
I've merged your PR, thanks!

**Comment by slokhorst** [comment]
Could you maybe bump the version number, so this change gets picked up by Composer?

**Comment by slokhorst** [comment]
Bump.. any chance of releasing a new version?

**Comment by stefandoorn** [comment]
@DaanBroekhof Could we release a new version to support PHP7? I'm having problems loadings Composer dependencies now due to this package being behind.

**Comment by MaartenScholder** [comment]
Good idea, I just made a release.

Sorry for the time it took after the PR.
