### ISSUE TITLE
No Postcode lookup in Magento backend via Order

### ISSUE THREAD

**Issue by Mic2005** [postcode-nl/PostcodeNl_Api_RestClient#6]
Hi developers, we switched to Magento CE 1.9.2.4 on PHP7. On Magento 1.7 we used the api lookup when we manual make the order. Now the lookup is only work when you go to customer, new customer but when you go to order, new order, new customer there is no automatic lookup, no fields like in the checkout. It worked fine in Magento 1.7 on PHP5.

Snapshot from new customer (address) via New Order:

![image](https://cloud.githubusercontent.com/assets/11639487/16042651/1420f818-323c-11e6-9056-92583a22abef.png)

Snapshot from new cusomer, new address via New Customer:

![image](https://cloud.githubusercontent.com/assets/11639487/16042793/d36b40ac-323c-11e6-9271-59f481416178.png)

Extension setting:

![image](https://cloud.githubusercontent.com/assets/11639487/16042683/387763e6-323c-11e6-92f2-6b4870f6fd57.png)

Can you reproduce this? Is there a fix?

**Comment by MaartenScholder** [comment]
This issue is actually related to https://github.com/postcode-nl/PostcodeNl_Api_MagentoPlugin specifically (the addon, which does use this client as implementation detail). However the Magento 1 addon will not receive any extra features and only the most critical fixes.
